/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as BankCardsRouteImport } from './routes/bank-cards'
import { Route as AtmRouteImport } from './routes/atm'
import { Route as IndexRouteImport } from './routes/index'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const BankCardsRoute = BankCardsRouteImport.update({
  id: '/bank-cards',
  path: '/bank-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AtmRoute = AtmRouteImport.update({
  id: '/atm',
  path: '/atm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atm': typeof AtmRoute
  '/bank-cards': typeof BankCardsRoute
  '/overview': typeof OverviewRoute
  '/schedules': typeof SchedulesRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atm': typeof AtmRoute
  '/bank-cards': typeof BankCardsRoute
  '/overview': typeof OverviewRoute
  '/schedules': typeof SchedulesRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atm': typeof AtmRoute
  '/bank-cards': typeof BankCardsRoute
  '/overview': typeof OverviewRoute
  '/schedules': typeof SchedulesRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atm'
    | '/bank-cards'
    | '/overview'
    | '/schedules'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atm'
    | '/bank-cards'
    | '/overview'
    | '/schedules'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/atm'
    | '/bank-cards'
    | '/overview'
    | '/schedules'
    | '/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtmRoute: typeof AtmRoute
  BankCardsRoute: typeof BankCardsRoute
  OverviewRoute: typeof OverviewRoute
  SchedulesRoute: typeof SchedulesRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-cards': {
      id: '/bank-cards'
      path: '/bank-cards'
      fullPath: '/bank-cards'
      preLoaderRoute: typeof BankCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atm': {
      id: '/atm'
      path: '/atm'
      fullPath: '/atm'
      preLoaderRoute: typeof AtmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtmRoute: AtmRoute,
  BankCardsRoute: BankCardsRoute,
  OverviewRoute: OverviewRoute,
  SchedulesRoute: SchedulesRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
